# Generated by Django 3.1.7 on 2021-05-02 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_auto_20210501_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appereances', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('yellow_card', models.IntegerField(default=0)),
                ('red_card', models.IntegerField(default=0)),
                ('football_position', models.CharField(choices=[('Manager', 'Manager'), ('Forward', 'Forward'), ('GK', 'GoalKeeper'), ('MID', 'Midfielder'), ('Defence', 'Defender')], max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
