# Generated by Django 3.1.7 on 2021-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20210502_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='assists',
            field=models.IntegerField(default=0),
        ),
    ]
