# Generated by Django 3.1.7 on 2021-05-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20210506_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='motm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
