# Generated by Django 3.1.7 on 2021-04-27 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('won', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('points', models.IntegerField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.team')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_match', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('venue', models.CharField(max_length=50)),
                ('competition', models.CharField(choices=[('League', 'League game'), ('Cup', 'Cup game')], max_length=30)),
                ('away_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='pages.team')),
                ('home_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='pages.team')),
            ],
        ),
    ]
