# Generated by Django 3.1.7 on 2021-04-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='goals_against',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standing',
            name='goals_for',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
