# Generated by Django 3.1.7 on 2021-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210428_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standing',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
