# Generated by Django 3.1.7 on 2021-04-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210428_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='points',
        ),
        migrations.RemoveField(
            model_name='standing',
            name='position',
        ),
    ]
