# Generated by Django 3.1.7 on 2021-04-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210428_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='games_played',
        ),
    ]
