# Generated by Django 3.1.7 on 2021-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_standing_games_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='competition',
            field=models.CharField(choices=[('League', 'League game'), ('Cup', 'Cup game')], default='League', max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
